CREATE OR REPLACE TRIGGER TRG_MIJLOC_FIX_INVENTAR_BEFORE_INSERT
BEFORE INSERT ON MIJLOC_FIX_INVENTAR
FOR EACH ROW
DECLARE
    dbUser VARCHAR2(20);
BEGIN
    SELECT USER INTO dbUser FROM dual;

    :NEW.creat_de := dbUser;
    :NEW.modificat_de := dbUser;
    :NEW.creat_la := SYSDATE;
END;
/
