CREATE OR REPLACE TRIGGER TRG_INVENTAR_BEFORE_UPDATE
BEFORE UPDATE ON INVENTAR
FOR EACH ROW
DECLARE
    dbUser VARCHAR2(20);
BEGIN
    SELECT USER INTO dbUser FROM dual;

    :NEW.modificat_de := dbUser;
    :NEW.modificat_la := SYSDATE;
END;
/
