CREATE OR REPLACE TRIGGER TRG_TIP_ENTITATE_BEFORE_INSERT
BEFORE INSERT ON TIP_ENTITATE
FOR EACH ROW
DECLARE
    dbUser VARCHAR2(20);
BEGIN
    SELECT USER INTO dbUser FROM dual;

    :NEW.creat_de := dbUser;
    :NEW.creat_la := SYSDATE;
END;
/
