CREATE OR REPLACE TRIGGER TRG_COMPANIE_BEFORE_UPDATE
BEFORE UPDATE ON COMPANIE
FOR EACH ROW
DECLARE
    dbUser VARCHAR2(20);
BEGIN

    SELECT User INTO dbUser FROM dual;

    :NEW.modificat_de := dbUser;
    :NEW.modificat_la := SYSDATE;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error in TRG_COMPANIE_BEFORE_UPDATE: ' || SQLERRM);
END;
/