CREATE OR REPLACE TRIGGER TRG_ANGAJAT_CENTRU_DE_COST_BEFORE_INSERT
BEFORE INSERT ON ANGAJAT_CENTRU_DE_COST
FOR EACH ROW
DECLARE
    dbUser VARCHAR2(20);
BEGIN
    SELECT USER INTO dbUser FROM dual;

    :NEW.creat_de := dbUser;
    :NEW.creat_la := SYSDATE;
END;
/
