CREATE OR REPLACE TRIGGER TRG_TIP_ENTITATE_BEFORE_UPDATE
BEFORE UPDATE ON TIP_ENTITATE
FOR EACH ROW
DECLARE
    dbUser VARCHAR2(20);
BEGIN
    SELECT USER INTO dbUser FROM dual;

    :NEW.modificat_de := dbUser;
    :NEW.modificat_la := SYSDATE;
END;
/
