CREATE OR REPLACE TRIGGER TRG_ANGAJAT_CENTRU_DE_COST_BEFORE_UPDATE
BEFORE UPDATE ON ANGAJAT_CENTRU_DE_COST
FOR EACH ROW
DECLARE
    dbUser VARCHAR2(20);
BEGIN
    SELECT USER INTO dbUser FROM dual;

    :NEW.modificat_de := dbUser;
    :NEW.modificat_la := SYSDATE;
END;
/
